# Site settings
title: Tangmi's Blog
email: '&#116;&#97;&#110;&#103;&#109;&#105;&#51;&#54;&#48;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;'
description: Tangmi's Blog
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  tangmi360
#permalink: /:year/:month/:day/:title/
permalink: /:title/

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
