# Site settings
title: tangmi的笔记本
email: tangmi360@gmail.com
description: tangmi的笔记本
baseurl: ""
url: "http://www.tangmi.me"
github_username: tangmi360

# Build settings
markdown: kramdown
permalink: /blog/:title

##
paginate: 10
paginate_path: "page:num"
